apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/retail-api-pod/
patchesStrategicMerge:
- ./kind-retail-api-patch.yaml
images:
- name: retail-api-image
  newName: retail-api-amd64
  newTag: "1.0"
